# Generated by Django 6.0.3 on 2026-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='editora',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estoque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
