# Generated by Django 6.0.3 on 2026-03-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_autor_id_alter_editora_id_alter_livro_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='livros',
            field=models.ManyToManyField(to='edu.livro'),
        ),
        migrations.DeleteModel(
            name='Publica',
        ),
    ]
